/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./public/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-container": "#202020",
        "surface-container-low": "#1b1b1c",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-bright": "#393939",
        "surface-dim": "#131313",
        "surface-variant": "#353535",
        "surface-tint": "#9fcaff",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c0c7d3",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#303030",
        outline: "#8a919d",
        "outline-variant": "#404751",
        primary: "#9fcaff",
        "primary-container": "#007acc",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#9fcaff",
        "on-primary": "#003258",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#001d36",
        "on-primary-fixed-variant": "#00497d",
        "inverse-primary": "#0061a4",
        secondary: "#84cfff",
        "secondary-container": "#019ad6",
        "secondary-fixed": "#c7e7ff",
        "secondary-fixed-dim": "#84cfff",
        "on-secondary": "#00344c",
        "on-secondary-container": "#002d42",
        "on-secondary-fixed": "#001e2e",
        "on-secondary-fixed-variant": "#004c6c",
        tertiary: "#f4b1ee",
        "tertiary-container": "#9d6299",
        "tertiary-fixed": "#ffd6f8",
        "tertiary-fixed-dim": "#f4b1ee",
        "on-tertiary": "#4e1c4f",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#350338",
        "on-tertiary-fixed-variant": "#683367",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
